name: Deploy to HuggingFace

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Important: fetch full history
      
      - name: Push to HuggingFace
        run: |
          git remote add hf https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/Image_Gen_Prompt_Engine
          git push hf main --force
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}