name: Deploy to HuggingFace

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Push to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://user:${HF_TOKEN}@huggingface.co/spaces/24Zyad/Image_Gen_Prompt_Engine
          git push hf main